"""Add status field to Suggestion

Revision ID: dc0b7730ca1e
Revises: e8414c5e116d
Create Date: 2026-04-01 11:34:34.724313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0b7730ca1e'
down_revision = 'e8414c5e116d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
